// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://vgddrhyjttyrathqhefb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnZGRyaHlqdHR5cmF0aHFoZWZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNDY4NTIsImV4cCI6MjA2MTYyMjg1Mn0.LMrdoexbaaIMdOa5TqS57nFlMMoSevqk3wXzfS1WXbE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
);
