// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// In development, use local Supabase instance
// In production, use the production Supabase instance
const isDevelopment = import.meta.env.DEV;

const SUPABASE_URL = isDevelopment
  ? 'http://localhost:54321'
  : 'https://vgddrhyjttyrathqhefb.supabase.co';

const SUPABASE_PUBLISHABLE_KEY = isDevelopment
  ? 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0'
  : 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnZGRyaHlqdHR5cmF0aHFoZWZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNDY4NTIsImV4cCI6MjA2MTYyMjg1Mn0.LMrdoexbaaIMdOa5TqS57nFlMMoSevqk3wXzfS1WXbE';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
